Repository DotBots/DotBot-firmware, pull requests merged in 2023-12, with the labels that each got.

#257 projects/03app_dotbot_gateway: fix crash on nrf5340dk
  projects/03app_dotbot_gateway/03app_dotbot_gateway.c
Labels: bug

#260 SailBot: Send radio data outside of the interrupt context
  projects/03app_sailbot/03app_sailbot.c
Labels: enhancement

#253 bsp: add basic SAADC driver
  bsp/bsp.emProject
  bsp/nrf/saadc.c
  bsp/saadc.h
  doc/sphinx/bsp.md
  doc/sphinx/examples.md
  projects/01bsp_saadc/01bsp_saadc.c
  projects/01bsp_saadc/README.md
  projects/projects-bsp-drv.emProject
Labels: new feature

#261 drv: add driver for lis3mdl magnetometer
  Makefile
  bsp/conf/dotbot_v2_config.h
  bsp/conf/nrf52833dk_config.h
  bsp/conf/nrf52840dk_config.h
  bsp/conf/nrf5340dk_config.h
  doc/sphinx/drv.md
  doc/sphinx/examples.md
  drv/drv.emProject
  drv/lis3mdl.h
  drv/lis3mdl/lis3mdl.c
  projects/01drv_lis3mdl/README.md
  projects/01drv_lis3mdl/main.c
  projects/projects-bsp-drv.emProject
Labels: new feature

#265 doc: fix DK board names in getting started page
  doc/sphinx/getting_started.md
Labels: documentation, cleanup

#266 projects/03app_dotbot_gateway: fix timing bug when using buttons to control a dotbot
  projects/03app_dotbot_gateway/03app_dotbot_gateway.c
Labels: bug

#267 projects/03app_dotbot_gateway: add user feedback using LEDs
  doc/sphinx/getting_started.md
  projects/03app_dotbot_gateway/03app_dotbot_gateway.c
Labels: enhancement
