Repository DotBots/DotBot-firmware, pull requests merged in 2025-01, with the labels that each got.

#349 swarmit: add dotbot sample application
  bsp/device.h
  bsp/nrf/lh2_default.c
  bsp/nrf/rng_nrf5340_app.c
  swarmit/cmse_implib.a
  swarmit/dotbot/README.md
  swarmit/dotbot/main.c
  swarmit/motors/main.c
  swarmit/move/main.c
  swarmit/rgbled/main.c
  swarmit/swarmit.emProject
  swarmit/timer/main.c
Labels: new feature

#356 Disable whitening for IEEE 8022.15.4 PHY
  bsp/nrf/radio_default.c
Labels: bug

#354 Refactor protocol packets format to enable layering
  bsp/ipc.h
  drv/drv.emProject
  drv/protocol.h
  drv/protocol/protocol.c
  drv/tdma_client.h
  drv/tdma_client/tdma_client_default.c
  drv/tdma_client/tdma_client_nrf5340_app.c
  drv/tdma_server.h
  drv/tdma_server/tdma_server_default.c
  drv/tdma_server/tdma_server_nrf5340_app.c
  projects/01drv_tdma_client/01drv_tdma_client.c
  projects/01drv_tdma_server/01drv_tdma_server.c
  projects/03app_dotbot/03app_dotbot.c
  projects/03app_dotbot_gateway/03app_dotbot_gateway.c
  projects/03app_freebot/main.c
  projects/03app_lh2_mini_mote_app/03app_lh2_mini_mote_app.c
  projects/03app_lh2_mini_mote_test/03app_lh2_mini_mote_test.c
  projects/03app_nrf5340_net/main.c
  projects/03app_sailbot/03app_sailbot.c
  projects/03app_xgo/main.c
Labels: enhancement
